# Parameters will be set by the Extension class

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\TusUploadServerBundle\Service\:
    resource: '../../Service/'
  Tourze\TusUploadServerBundle\Handler\:
    resource: '../../Handler/'
  Tourze\TusUploadServerBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']
    public: true
  Tourze\TusUploadServerBundle\Command\:
    resource: '../../Command/'
  Tourze\TusUploadServerBundle\Repository\:
    resource: '../../Repository/'

  # Filesystem configuration
  tus_upload.filesystem:
    class: League\Flysystem\FilesystemOperator
    factory: ['@Tourze\TusUploadServerBundle\Service\FilesystemFactory', 'createLocalFilesystem']

  # Override the service binding
  Tourze\TusUploadServerBundle\Service\TusUploadService:
    arguments:
      $filesystem: '@tus_upload.filesystem'
      $uploadPath: 'uploads'
